before_script:
    - apt-get update -qq
    - apt-get install -qq git
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$K8S_SECRET_SSH_PRIVATE_KEY"
    - ssh-add <(echo "$K8S_SECRET_SSH_PRIVATE_KEY" | base64 -d)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_staging:
    type: deploy
    environment:
        name: staging
        url: 206.189.48.29
    script:
      - ssh root@206.189.48.29 -p 1312 "cd /home/sites/zartoshtsepideman.com/www/public && git checkout master && git pull origin master && chown www-data:www-data . -R && exit"
    only:
      - master
